name: donote
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_auth:
    git:
      url: https://github.com/kallsodev/easy_auth.git
      ref: main
  easy_utils:
    git:
      url: https://github.com/kallsodev/easy_utils.git
      ref: main

  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  flutter_quill: ^6.1.11
  cloud_firestore: ^4.3.0
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  equatable: ^2.0.5
  timeago: ^3.3.0
  flutter_colorpicker: ^1.0.3
  hive_generator: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

  assets:
    - assets/images/
    - assets/